// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from message.proto</summary>
public static partial class MessageReflection {

  #region Descriptor
  /// <summary>File descriptor for message.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1tZXNzYWdlLnByb3RvIjUKC0xvYWRJY29uUmVxEhMKBGNzaWQYASABKA4y",
          "BS5DU0lEEhEKCWljb25MYWJlbBgCIAMoCSJICgtMb2FkSWNvblJlcxITCgRj",
          "c2lkGAEgASgOMgUuQ1NJRBIRCglpY29uTGFiZWwYAiADKAkSEQoJaW1hZ2VE",
          "YXRhGAMgAygMIj0KE0FBQ0Rpc3BlcnNlSWNvblNlbmQSEwoEY3NpZBgBIAEo",
          "DjIFLkNTSUQSEQoJaWNvbkxhYmVsGAIgAygJIpABChVBQUNEaXNwZXJzZUlj",
          "b25Ub1RleHQSEwoEY3NpZBgBIAEoDjIFLkNTSUQSDAoEdGV4dBgCIAEoCRIk",
          "Cgt0ZXh0RW1vdGlvbhgDIAEoCzIPLkFBQ1RleHRFbW90aW9uEi4KEHByZWRp",
          "Y3RJY29uTGFiZWwYBCABKAsyFC5BQUNQcmVkaWN0SWNvbkxhYmVsIiIKE0Nv",
          "bm5lY3RDaGVja1JlcXVlc3QSCwoDbXNnGAEgASgJIlIKFENvbm5lY3RDaGVj",
          "a1Jlc3BvbnNlEg8KB2Nvbm5lY3QYASABKAgSFwoGcmVzdWx0GAIgASgOMgcu",
          "UkVTVUxUEhAKCGVycm9ybXNnGAMgASgJIj8KDkFBQ1RleHRFbW90aW9uEhYK",
          "DmN1cnJlbnRFbW90aW9uGAEgASgJEhUKDUdsb2JhbEVtb3Rpb24YAiABKAki",
          "KAoTQUFDUHJlZGljdEljb25MYWJlbBIRCglpY29uTGFiZWwYASABKAkqIQoG",
          "UkVTVUxUEgsKB1NVQ0NFU1MQABIKCgZGQUlMRUQQASqzAQoEQ1NJRBIbChdD",
          "U0lEX0NPTk5FQ1RfU1VDQ0VTU0ZVTBAAEhcKE0NTSURfQ09OTkVDVF9GQUlM",
          "RUQQARIgChxDU0lEX0FBQ19ESVNQRVJTRVNfSUNPTl9TRU5EEAISIwofQ1NJ",
          "RF9BQUNfRElTUEVSU0VTX0lDT05fVE9fVEVYVBADEhYKEkNTSURfTE9BRF9J",
          "Q09OX1JFURAEEhYKEkNTSURfTE9BRF9JQ09OX1JFUxAFMrEBCgdTZXJ2aWNl",
          "EjsKDENvbm5lY3RDaGVjaxIULkNvbm5lY3RDaGVja1JlcXVlc3QaFS5Db25u",
          "ZWN0Q2hlY2tSZXNwb25zZRJBChFQcm9jZXNzQUFDTWVzc2FnZRIULkFBQ0Rp",
          "c3BlcnNlSWNvblNlbmQaFi5BQUNEaXNwZXJzZUljb25Ub1RleHQSJgoITG9h",
          "ZEljb24SDC5Mb2FkSWNvblJlcRoMLkxvYWRJY29uUmVzYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::RESULT), typeof(global::CSID), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::LoadIconReq), global::LoadIconReq.Parser, new[]{ "Csid", "IconLabel" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LoadIconRes), global::LoadIconRes.Parser, new[]{ "Csid", "IconLabel", "ImageData" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AACDisperseIconSend), global::AACDisperseIconSend.Parser, new[]{ "Csid", "IconLabel" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AACDisperseIconToText), global::AACDisperseIconToText.Parser, new[]{ "Csid", "Text", "TextEmotion", "PredictIconLabel" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ConnectCheckRequest), global::ConnectCheckRequest.Parser, new[]{ "Msg" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ConnectCheckResponse), global::ConnectCheckResponse.Parser, new[]{ "Connect", "Result", "Errormsg" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AACTextEmotion), global::AACTextEmotion.Parser, new[]{ "CurrentEmotion", "GlobalEmotion" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AACPredictIconLabel), global::AACPredictIconLabel.Parser, new[]{ "IconLabel" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum RESULT {
  [pbr::OriginalName("SUCCESS")] Success = 0,
  [pbr::OriginalName("FAILED")] Failed = 1,
}

public enum CSID {
  [pbr::OriginalName("CSID_CONNECT_SUCCESSFUL")] ConnectSuccessful = 0,
  [pbr::OriginalName("CSID_CONNECT_FAILED")] ConnectFailed = 1,
  [pbr::OriginalName("CSID_AAC_DISPERSES_ICON_SEND")] AacDispersesIconSend = 2,
  [pbr::OriginalName("CSID_AAC_DISPERSES_ICON_TO_TEXT")] AacDispersesIconToText = 3,
  [pbr::OriginalName("CSID_LOAD_ICON_REQ")] LoadIconReq = 4,
  [pbr::OriginalName("CSID_LOAD_ICON_RES")] LoadIconRes = 5,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class LoadIconReq : pb::IMessage<LoadIconReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LoadIconReq> _parser = new pb::MessageParser<LoadIconReq>(() => new LoadIconReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LoadIconReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoadIconReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoadIconReq(LoadIconReq other) : this() {
    csid_ = other.csid_;
    iconLabel_ = other.iconLabel_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoadIconReq Clone() {
    return new LoadIconReq(this);
  }

  /// <summary>Field number for the "csid" field.</summary>
  public const int CsidFieldNumber = 1;
  private global::CSID csid_ = global::CSID.ConnectSuccessful;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CSID Csid {
    get { return csid_; }
    set {
      csid_ = value;
    }
  }

  /// <summary>Field number for the "iconLabel" field.</summary>
  public const int IconLabelFieldNumber = 2;
  private static readonly pb::FieldCodec<string> _repeated_iconLabel_codec
      = pb::FieldCodec.ForString(18);
  private readonly pbc::RepeatedField<string> iconLabel_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> IconLabel {
    get { return iconLabel_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LoadIconReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LoadIconReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Csid != other.Csid) return false;
    if(!iconLabel_.Equals(other.iconLabel_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Csid != global::CSID.ConnectSuccessful) hash ^= Csid.GetHashCode();
    hash ^= iconLabel_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Csid != global::CSID.ConnectSuccessful) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Csid);
    }
    iconLabel_.WriteTo(output, _repeated_iconLabel_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Csid != global::CSID.ConnectSuccessful) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Csid);
    }
    iconLabel_.WriteTo(ref output, _repeated_iconLabel_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Csid != global::CSID.ConnectSuccessful) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Csid);
    }
    size += iconLabel_.CalculateSize(_repeated_iconLabel_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LoadIconReq other) {
    if (other == null) {
      return;
    }
    if (other.Csid != global::CSID.ConnectSuccessful) {
      Csid = other.Csid;
    }
    iconLabel_.Add(other.iconLabel_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Csid = (global::CSID) input.ReadEnum();
          break;
        }
        case 18: {
          iconLabel_.AddEntriesFrom(input, _repeated_iconLabel_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Csid = (global::CSID) input.ReadEnum();
          break;
        }
        case 18: {
          iconLabel_.AddEntriesFrom(ref input, _repeated_iconLabel_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class LoadIconRes : pb::IMessage<LoadIconRes>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LoadIconRes> _parser = new pb::MessageParser<LoadIconRes>(() => new LoadIconRes());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LoadIconRes> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoadIconRes() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoadIconRes(LoadIconRes other) : this() {
    csid_ = other.csid_;
    iconLabel_ = other.iconLabel_.Clone();
    imageData_ = other.imageData_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoadIconRes Clone() {
    return new LoadIconRes(this);
  }

  /// <summary>Field number for the "csid" field.</summary>
  public const int CsidFieldNumber = 1;
  private global::CSID csid_ = global::CSID.ConnectSuccessful;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CSID Csid {
    get { return csid_; }
    set {
      csid_ = value;
    }
  }

  /// <summary>Field number for the "iconLabel" field.</summary>
  public const int IconLabelFieldNumber = 2;
  private static readonly pb::FieldCodec<string> _repeated_iconLabel_codec
      = pb::FieldCodec.ForString(18);
  private readonly pbc::RepeatedField<string> iconLabel_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> IconLabel {
    get { return iconLabel_; }
  }

  /// <summary>Field number for the "imageData" field.</summary>
  public const int ImageDataFieldNumber = 3;
  private static readonly pb::FieldCodec<pb::ByteString> _repeated_imageData_codec
      = pb::FieldCodec.ForBytes(26);
  private readonly pbc::RepeatedField<pb::ByteString> imageData_ = new pbc::RepeatedField<pb::ByteString>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<pb::ByteString> ImageData {
    get { return imageData_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LoadIconRes);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LoadIconRes other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Csid != other.Csid) return false;
    if(!iconLabel_.Equals(other.iconLabel_)) return false;
    if(!imageData_.Equals(other.imageData_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Csid != global::CSID.ConnectSuccessful) hash ^= Csid.GetHashCode();
    hash ^= iconLabel_.GetHashCode();
    hash ^= imageData_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Csid != global::CSID.ConnectSuccessful) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Csid);
    }
    iconLabel_.WriteTo(output, _repeated_iconLabel_codec);
    imageData_.WriteTo(output, _repeated_imageData_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Csid != global::CSID.ConnectSuccessful) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Csid);
    }
    iconLabel_.WriteTo(ref output, _repeated_iconLabel_codec);
    imageData_.WriteTo(ref output, _repeated_imageData_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Csid != global::CSID.ConnectSuccessful) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Csid);
    }
    size += iconLabel_.CalculateSize(_repeated_iconLabel_codec);
    size += imageData_.CalculateSize(_repeated_imageData_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LoadIconRes other) {
    if (other == null) {
      return;
    }
    if (other.Csid != global::CSID.ConnectSuccessful) {
      Csid = other.Csid;
    }
    iconLabel_.Add(other.iconLabel_);
    imageData_.Add(other.imageData_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Csid = (global::CSID) input.ReadEnum();
          break;
        }
        case 18: {
          iconLabel_.AddEntriesFrom(input, _repeated_iconLabel_codec);
          break;
        }
        case 26: {
          imageData_.AddEntriesFrom(input, _repeated_imageData_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Csid = (global::CSID) input.ReadEnum();
          break;
        }
        case 18: {
          iconLabel_.AddEntriesFrom(ref input, _repeated_iconLabel_codec);
          break;
        }
        case 26: {
          imageData_.AddEntriesFrom(ref input, _repeated_imageData_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AACDisperseIconSend : pb::IMessage<AACDisperseIconSend>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AACDisperseIconSend> _parser = new pb::MessageParser<AACDisperseIconSend>(() => new AACDisperseIconSend());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AACDisperseIconSend> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AACDisperseIconSend() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AACDisperseIconSend(AACDisperseIconSend other) : this() {
    csid_ = other.csid_;
    iconLabel_ = other.iconLabel_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AACDisperseIconSend Clone() {
    return new AACDisperseIconSend(this);
  }

  /// <summary>Field number for the "csid" field.</summary>
  public const int CsidFieldNumber = 1;
  private global::CSID csid_ = global::CSID.ConnectSuccessful;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CSID Csid {
    get { return csid_; }
    set {
      csid_ = value;
    }
  }

  /// <summary>Field number for the "iconLabel" field.</summary>
  public const int IconLabelFieldNumber = 2;
  private static readonly pb::FieldCodec<string> _repeated_iconLabel_codec
      = pb::FieldCodec.ForString(18);
  private readonly pbc::RepeatedField<string> iconLabel_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> IconLabel {
    get { return iconLabel_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AACDisperseIconSend);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AACDisperseIconSend other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Csid != other.Csid) return false;
    if(!iconLabel_.Equals(other.iconLabel_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Csid != global::CSID.ConnectSuccessful) hash ^= Csid.GetHashCode();
    hash ^= iconLabel_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Csid != global::CSID.ConnectSuccessful) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Csid);
    }
    iconLabel_.WriteTo(output, _repeated_iconLabel_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Csid != global::CSID.ConnectSuccessful) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Csid);
    }
    iconLabel_.WriteTo(ref output, _repeated_iconLabel_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Csid != global::CSID.ConnectSuccessful) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Csid);
    }
    size += iconLabel_.CalculateSize(_repeated_iconLabel_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AACDisperseIconSend other) {
    if (other == null) {
      return;
    }
    if (other.Csid != global::CSID.ConnectSuccessful) {
      Csid = other.Csid;
    }
    iconLabel_.Add(other.iconLabel_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Csid = (global::CSID) input.ReadEnum();
          break;
        }
        case 18: {
          iconLabel_.AddEntriesFrom(input, _repeated_iconLabel_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Csid = (global::CSID) input.ReadEnum();
          break;
        }
        case 18: {
          iconLabel_.AddEntriesFrom(ref input, _repeated_iconLabel_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AACDisperseIconToText : pb::IMessage<AACDisperseIconToText>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AACDisperseIconToText> _parser = new pb::MessageParser<AACDisperseIconToText>(() => new AACDisperseIconToText());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AACDisperseIconToText> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AACDisperseIconToText() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AACDisperseIconToText(AACDisperseIconToText other) : this() {
    csid_ = other.csid_;
    text_ = other.text_;
    textEmotion_ = other.textEmotion_ != null ? other.textEmotion_.Clone() : null;
    predictIconLabel_ = other.predictIconLabel_ != null ? other.predictIconLabel_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AACDisperseIconToText Clone() {
    return new AACDisperseIconToText(this);
  }

  /// <summary>Field number for the "csid" field.</summary>
  public const int CsidFieldNumber = 1;
  private global::CSID csid_ = global::CSID.ConnectSuccessful;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CSID Csid {
    get { return csid_; }
    set {
      csid_ = value;
    }
  }

  /// <summary>Field number for the "text" field.</summary>
  public const int TextFieldNumber = 2;
  private string text_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Text {
    get { return text_; }
    set {
      text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "textEmotion" field.</summary>
  public const int TextEmotionFieldNumber = 3;
  private global::AACTextEmotion textEmotion_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::AACTextEmotion TextEmotion {
    get { return textEmotion_; }
    set {
      textEmotion_ = value;
    }
  }

  /// <summary>Field number for the "predictIconLabel" field.</summary>
  public const int PredictIconLabelFieldNumber = 4;
  private global::AACPredictIconLabel predictIconLabel_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::AACPredictIconLabel PredictIconLabel {
    get { return predictIconLabel_; }
    set {
      predictIconLabel_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AACDisperseIconToText);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AACDisperseIconToText other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Csid != other.Csid) return false;
    if (Text != other.Text) return false;
    if (!object.Equals(TextEmotion, other.TextEmotion)) return false;
    if (!object.Equals(PredictIconLabel, other.PredictIconLabel)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Csid != global::CSID.ConnectSuccessful) hash ^= Csid.GetHashCode();
    if (Text.Length != 0) hash ^= Text.GetHashCode();
    if (textEmotion_ != null) hash ^= TextEmotion.GetHashCode();
    if (predictIconLabel_ != null) hash ^= PredictIconLabel.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Csid != global::CSID.ConnectSuccessful) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Csid);
    }
    if (Text.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Text);
    }
    if (textEmotion_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(TextEmotion);
    }
    if (predictIconLabel_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(PredictIconLabel);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Csid != global::CSID.ConnectSuccessful) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Csid);
    }
    if (Text.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Text);
    }
    if (textEmotion_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(TextEmotion);
    }
    if (predictIconLabel_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(PredictIconLabel);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Csid != global::CSID.ConnectSuccessful) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Csid);
    }
    if (Text.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
    }
    if (textEmotion_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(TextEmotion);
    }
    if (predictIconLabel_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(PredictIconLabel);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AACDisperseIconToText other) {
    if (other == null) {
      return;
    }
    if (other.Csid != global::CSID.ConnectSuccessful) {
      Csid = other.Csid;
    }
    if (other.Text.Length != 0) {
      Text = other.Text;
    }
    if (other.textEmotion_ != null) {
      if (textEmotion_ == null) {
        TextEmotion = new global::AACTextEmotion();
      }
      TextEmotion.MergeFrom(other.TextEmotion);
    }
    if (other.predictIconLabel_ != null) {
      if (predictIconLabel_ == null) {
        PredictIconLabel = new global::AACPredictIconLabel();
      }
      PredictIconLabel.MergeFrom(other.PredictIconLabel);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Csid = (global::CSID) input.ReadEnum();
          break;
        }
        case 18: {
          Text = input.ReadString();
          break;
        }
        case 26: {
          if (textEmotion_ == null) {
            TextEmotion = new global::AACTextEmotion();
          }
          input.ReadMessage(TextEmotion);
          break;
        }
        case 34: {
          if (predictIconLabel_ == null) {
            PredictIconLabel = new global::AACPredictIconLabel();
          }
          input.ReadMessage(PredictIconLabel);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Csid = (global::CSID) input.ReadEnum();
          break;
        }
        case 18: {
          Text = input.ReadString();
          break;
        }
        case 26: {
          if (textEmotion_ == null) {
            TextEmotion = new global::AACTextEmotion();
          }
          input.ReadMessage(TextEmotion);
          break;
        }
        case 34: {
          if (predictIconLabel_ == null) {
            PredictIconLabel = new global::AACPredictIconLabel();
          }
          input.ReadMessage(PredictIconLabel);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ConnectCheckRequest : pb::IMessage<ConnectCheckRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ConnectCheckRequest> _parser = new pb::MessageParser<ConnectCheckRequest>(() => new ConnectCheckRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ConnectCheckRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ConnectCheckRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ConnectCheckRequest(ConnectCheckRequest other) : this() {
    msg_ = other.msg_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ConnectCheckRequest Clone() {
    return new ConnectCheckRequest(this);
  }

  /// <summary>Field number for the "msg" field.</summary>
  public const int MsgFieldNumber = 1;
  private string msg_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Msg {
    get { return msg_; }
    set {
      msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ConnectCheckRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ConnectCheckRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Msg != other.Msg) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Msg.Length != 0) hash ^= Msg.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Msg.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Msg);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Msg.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Msg);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Msg.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ConnectCheckRequest other) {
    if (other == null) {
      return;
    }
    if (other.Msg.Length != 0) {
      Msg = other.Msg;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Msg = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Msg = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ConnectCheckResponse : pb::IMessage<ConnectCheckResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ConnectCheckResponse> _parser = new pb::MessageParser<ConnectCheckResponse>(() => new ConnectCheckResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ConnectCheckResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ConnectCheckResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ConnectCheckResponse(ConnectCheckResponse other) : this() {
    connect_ = other.connect_;
    result_ = other.result_;
    errormsg_ = other.errormsg_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ConnectCheckResponse Clone() {
    return new ConnectCheckResponse(this);
  }

  /// <summary>Field number for the "connect" field.</summary>
  public const int ConnectFieldNumber = 1;
  private bool connect_;
  /// <summary>
  ///连接成功
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Connect {
    get { return connect_; }
    set {
      connect_ = value;
    }
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 2;
  private global::RESULT result_ = global::RESULT.Success;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::RESULT Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  /// <summary>Field number for the "errormsg" field.</summary>
  public const int ErrormsgFieldNumber = 3;
  private string errormsg_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Errormsg {
    get { return errormsg_; }
    set {
      errormsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ConnectCheckResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ConnectCheckResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Connect != other.Connect) return false;
    if (Result != other.Result) return false;
    if (Errormsg != other.Errormsg) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Connect != false) hash ^= Connect.GetHashCode();
    if (Result != global::RESULT.Success) hash ^= Result.GetHashCode();
    if (Errormsg.Length != 0) hash ^= Errormsg.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Connect != false) {
      output.WriteRawTag(8);
      output.WriteBool(Connect);
    }
    if (Result != global::RESULT.Success) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Result);
    }
    if (Errormsg.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Errormsg);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Connect != false) {
      output.WriteRawTag(8);
      output.WriteBool(Connect);
    }
    if (Result != global::RESULT.Success) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Result);
    }
    if (Errormsg.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Errormsg);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Connect != false) {
      size += 1 + 1;
    }
    if (Result != global::RESULT.Success) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
    }
    if (Errormsg.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Errormsg);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ConnectCheckResponse other) {
    if (other == null) {
      return;
    }
    if (other.Connect != false) {
      Connect = other.Connect;
    }
    if (other.Result != global::RESULT.Success) {
      Result = other.Result;
    }
    if (other.Errormsg.Length != 0) {
      Errormsg = other.Errormsg;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Connect = input.ReadBool();
          break;
        }
        case 16: {
          Result = (global::RESULT) input.ReadEnum();
          break;
        }
        case 26: {
          Errormsg = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Connect = input.ReadBool();
          break;
        }
        case 16: {
          Result = (global::RESULT) input.ReadEnum();
          break;
        }
        case 26: {
          Errormsg = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AACTextEmotion : pb::IMessage<AACTextEmotion>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AACTextEmotion> _parser = new pb::MessageParser<AACTextEmotion>(() => new AACTextEmotion());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AACTextEmotion> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AACTextEmotion() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AACTextEmotion(AACTextEmotion other) : this() {
    currentEmotion_ = other.currentEmotion_;
    globalEmotion_ = other.globalEmotion_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AACTextEmotion Clone() {
    return new AACTextEmotion(this);
  }

  /// <summary>Field number for the "currentEmotion" field.</summary>
  public const int CurrentEmotionFieldNumber = 1;
  private string currentEmotion_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CurrentEmotion {
    get { return currentEmotion_; }
    set {
      currentEmotion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "GlobalEmotion" field.</summary>
  public const int GlobalEmotionFieldNumber = 2;
  private string globalEmotion_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GlobalEmotion {
    get { return globalEmotion_; }
    set {
      globalEmotion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AACTextEmotion);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AACTextEmotion other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CurrentEmotion != other.CurrentEmotion) return false;
    if (GlobalEmotion != other.GlobalEmotion) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (CurrentEmotion.Length != 0) hash ^= CurrentEmotion.GetHashCode();
    if (GlobalEmotion.Length != 0) hash ^= GlobalEmotion.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (CurrentEmotion.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(CurrentEmotion);
    }
    if (GlobalEmotion.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(GlobalEmotion);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (CurrentEmotion.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(CurrentEmotion);
    }
    if (GlobalEmotion.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(GlobalEmotion);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (CurrentEmotion.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentEmotion);
    }
    if (GlobalEmotion.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(GlobalEmotion);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AACTextEmotion other) {
    if (other == null) {
      return;
    }
    if (other.CurrentEmotion.Length != 0) {
      CurrentEmotion = other.CurrentEmotion;
    }
    if (other.GlobalEmotion.Length != 0) {
      GlobalEmotion = other.GlobalEmotion;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          CurrentEmotion = input.ReadString();
          break;
        }
        case 18: {
          GlobalEmotion = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          CurrentEmotion = input.ReadString();
          break;
        }
        case 18: {
          GlobalEmotion = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AACPredictIconLabel : pb::IMessage<AACPredictIconLabel>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AACPredictIconLabel> _parser = new pb::MessageParser<AACPredictIconLabel>(() => new AACPredictIconLabel());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AACPredictIconLabel> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AACPredictIconLabel() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AACPredictIconLabel(AACPredictIconLabel other) : this() {
    iconLabel_ = other.iconLabel_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AACPredictIconLabel Clone() {
    return new AACPredictIconLabel(this);
  }

  /// <summary>Field number for the "iconLabel" field.</summary>
  public const int IconLabelFieldNumber = 1;
  private string iconLabel_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string IconLabel {
    get { return iconLabel_; }
    set {
      iconLabel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AACPredictIconLabel);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AACPredictIconLabel other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (IconLabel != other.IconLabel) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (IconLabel.Length != 0) hash ^= IconLabel.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (IconLabel.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(IconLabel);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (IconLabel.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(IconLabel);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (IconLabel.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(IconLabel);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AACPredictIconLabel other) {
    if (other == null) {
      return;
    }
    if (other.IconLabel.Length != 0) {
      IconLabel = other.IconLabel;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          IconLabel = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          IconLabel = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
