# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import message_pb2 as message__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in message_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectCheck = channel.unary_unary(
                '/Service/ConnectCheck',
                request_serializer=message__pb2.ConnectCheckRequest.SerializeToString,
                response_deserializer=message__pb2.ConnectCheckResponse.FromString,
                _registered_method=True)
        self.ProcessAACMessage = channel.unary_unary(
                '/Service/ProcessAACMessage',
                request_serializer=message__pb2.AACDisperseIconSend.SerializeToString,
                response_deserializer=message__pb2.AACDisperseIconToText.FromString,
                _registered_method=True)
        self.LoadIcon = channel.unary_unary(
                '/Service/LoadIcon',
                request_serializer=message__pb2.LoadIconReq.SerializeToString,
                response_deserializer=message__pb2.LoadIconRes.FromString,
                _registered_method=True)


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConnectCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessAACMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadIcon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectCheck,
                    request_deserializer=message__pb2.ConnectCheckRequest.FromString,
                    response_serializer=message__pb2.ConnectCheckResponse.SerializeToString,
            ),
            'ProcessAACMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAACMessage,
                    request_deserializer=message__pb2.AACDisperseIconSend.FromString,
                    response_serializer=message__pb2.AACDisperseIconToText.SerializeToString,
            ),
            'LoadIcon': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadIcon,
                    request_deserializer=message__pb2.LoadIconReq.FromString,
                    response_serializer=message__pb2.LoadIconRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Service/ConnectCheck',
            message__pb2.ConnectCheckRequest.SerializeToString,
            message__pb2.ConnectCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessAACMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Service/ProcessAACMessage',
            message__pb2.AACDisperseIconSend.SerializeToString,
            message__pb2.AACDisperseIconToText.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadIcon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Service/LoadIcon',
            message__pb2.LoadIconReq.SerializeToString,
            message__pb2.LoadIconRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
